### ISSUE TITLE
Make restart capacity more intelligent

### ISSUE THREAD

**Issue by firsttempora** [CohenBerkeleyLab/AutoWRFChem-Base#20]
Two things:
1) It should only look for restart files in the time period specified and should check that they represent the same domain as set in the namelist
2) If restart is specified and no restart files available, should it crash (as done now) or just start from the beginning? These could be determined by a flag.

**Comment by behr-github** [comment]
Handled in 27000afdc7984c4081308f898f3dd05e2f04cf1b. Did not include domain checking, that is probably done in WRF itself.
